#goal3: {"x": 6.43, "y": 6.76, "w": 120}
goal3: {"x": 5.67, "y": 7.44, "w": 270}

#goal1: {"x": 5.1, "y": 9.4, "w": -60}
goal1: {"x": 4.1, "y": 9.8, "w": 270}

#goal2: {"x": 5.2, "y": 8.2, "w": -60}
goal2: {"x": 4.98, "y": 8.82, "w": 270}
#goal2: {"x": 6.1, "y": 8.8, "w": -60}


