goal_s:
  x: 4.93
  y: 9.63
  w: -30
  photo_name: 'goal_s.png'

goal_r:
  x: 5.24
  y: 8.38
  w: -30
  photo_name: 'goal_r.png'

goal_l:
  x: 5.95
  y: 9.06
  w: -30
  photo_name: 'goal_l.png'

goal_t:
  x: 5.57
  y: 6.93
  w: -30
  photo_name: 'goal_t.png'

img_topic: '/usb_cam/image_raw'
